#DATABASE PROPERTIES
dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.168.99.100:5432/multimedia
  username: multimedia
  password: root
  dialect: org.hibernate.dialect.PostgreSQLDialect
  package: org.yakimovdenis.multimedia.models

liquibase:
  enabled: false